// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121140538_Add_CustomerCountry")]
    partial class Add_CustomerCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelsLayer.Bookings", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<short?>("CreatedBy")
                        .HasColumnType("smallint");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<byte>("PassengerCount")
                        .HasColumnType("tinyint");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerID");

                    b.HasIndex("TripID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ModelsLayer.Buses", b =>
                {
                    b.Property<short>("BusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("BusID"));

                    b.Property<string>("BusModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("CreatedByUserID")
                        .HasColumnType("smallint");

                    b.Property<short>("DriverID")
                        .HasColumnType("smallint");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("YearOfMananufacture")
                        .HasColumnType("datetime2");

                    b.HasKey("BusID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("DriverID");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("ModelsLayer.Cities", b =>
                {
                    b.Property<short>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("CountryID")
                        .HasColumnType("smallint");

                    b.HasKey("CityID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = (short)1,
                            CityName = "Amman",
                            CountryID = (short)1
                        },
                        new
                        {
                            CityID = (short)2,
                            CityName = "Zarqa",
                            CountryID = (short)1
                        },
                        new
                        {
                            CityID = (short)3,
                            CityName = "Irbid",
                            CountryID = (short)1
                        },
                        new
                        {
                            CityID = (short)4,
                            CityName = "Aqaba",
                            CountryID = (short)1
                        },
                        new
                        {
                            CityID = (short)5,
                            CityName = "Cairo",
                            CountryID = (short)2
                        },
                        new
                        {
                            CityID = (short)6,
                            CityName = "Alexandria",
                            CountryID = (short)2
                        },
                        new
                        {
                            CityID = (short)7,
                            CityName = "Giza",
                            CountryID = (short)2
                        },
                        new
                        {
                            CityID = (short)8,
                            CityName = "Sharm Elshiekh",
                            CountryID = (short)2
                        },
                        new
                        {
                            CityID = (short)9,
                            CityName = "Damascus",
                            CountryID = (short)3
                        },
                        new
                        {
                            CityID = (short)10,
                            CityName = "Aleppo",
                            CountryID = (short)3
                        },
                        new
                        {
                            CityID = (short)11,
                            CityName = "Homs",
                            CountryID = (short)3
                        },
                        new
                        {
                            CityID = (short)12,
                            CityName = "Baghdad",
                            CountryID = (short)4
                        },
                        new
                        {
                            CityID = (short)13,
                            CityName = "Basra",
                            CountryID = (short)4
                        },
                        new
                        {
                            CityID = (short)14,
                            CityName = "Mosul",
                            CountryID = (short)4
                        });
                });

            modelBuilder.Entity("ModelsLayer.Countries", b =>
                {
                    b.Property<short>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CountryID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = (short)1,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryID = (short)2,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryID = (short)3,
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryID = (short)4,
                            CountryName = "Iraq"
                        });
                });

            modelBuilder.Entity("ModelsLayer.Customers", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<short?>("CustomersCountriesCountryID")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerID");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomersCountriesCountryID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ModelsLayer.CustomersCountries", b =>
                {
                    b.Property<short>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CountryID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryID");

                    b.ToTable("CustomersCountries");
                });

            modelBuilder.Entity("ModelsLayer.Drivers", b =>
                {
                    b.Property<short>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DriverID"));

                    b.Property<short>("CreatedByUserID")
                        .HasColumnType("smallint");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DriverRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DriverID");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("ModelsLayer.Payments", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ModelsLayer.RoutePrices", b =>
                {
                    b.Property<short>("RoutePriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RoutePriceID"));

                    b.Property<short>("CreatedByUserID")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<short>("RouteID")
                        .HasColumnType("smallint");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TravelClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoutePriceID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RouteID");

                    b.ToTable("RoutePrices");
                });

            modelBuilder.Entity("ModelsLayer.Routes", b =>
                {
                    b.Property<short>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RouteID"));

                    b.Property<short>("CreatedByUserID")
                        .HasColumnType("smallint");

                    b.Property<double>("DistanceKM")
                        .HasColumnType("float");

                    b.Property<short>("FromCityID")
                        .HasColumnType("smallint");

                    b.Property<short>("FromCountryID")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ToCityID")
                        .HasColumnType("smallint");

                    b.Property<short?>("ToCountryID")
                        .HasColumnType("smallint");

                    b.HasKey("RouteID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("FromCityID");

                    b.HasIndex("FromCountryID");

                    b.HasIndex("ToCityID");

                    b.HasIndex("ToCountryID");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ModelsLayer.Tickets", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("SeatNumber")
                        .HasColumnType("tinyint");

                    b.HasKey("TicketID");

                    b.HasIndex("BookingID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ModelsLayer.Trips", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripID"));

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<byte>("AvailableSeats")
                        .HasColumnType("tinyint");

                    b.Property<short>("BusID")
                        .HasColumnType("smallint");

                    b.Property<short>("CreatedByUserID")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<short>("RouteID")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TripID");

                    b.HasIndex("BusID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RouteID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("ModelsLayer.Users", b =>
                {
                    b.Property<short>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("UserID"));

                    b.Property<string>("ImgPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModelsLayer.Bookings", b =>
                {
                    b.HasOne("ModelsLayer.Users", "CreatedByUser")
                        .WithMany("Booking")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModelsLayer.Customers", "Customer")
                        .WithMany("Booking")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Trips", "Trip")
                        .WithMany("Booking")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("ModelsLayer.Buses", b =>
                {
                    b.HasOne("ModelsLayer.Users", "CreatedByUser")
                        .WithMany("Bus")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Drivers", "Driver")
                        .WithMany("Bus")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ModelsLayer.Cities", b =>
                {
                    b.HasOne("ModelsLayer.Countries", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ModelsLayer.Customers", b =>
                {
                    b.HasOne("ModelsLayer.Countries", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.CustomersCountries", null)
                        .WithMany("Customers")
                        .HasForeignKey("CustomersCountriesCountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ModelsLayer.Drivers", b =>
                {
                    b.HasOne("ModelsLayer.Users", "CreatedByUser")
                        .WithMany("Driver")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ModelsLayer.Payments", b =>
                {
                    b.HasOne("ModelsLayer.Bookings", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("ModelsLayer.Payments", "BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ModelsLayer.RoutePrices", b =>
                {
                    b.HasOne("ModelsLayer.Users", "CreatedByUser")
                        .WithMany("RoutPrice")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Routes", "Route")
                        .WithMany("RoutePrice")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ModelsLayer.Routes", b =>
                {
                    b.HasOne("ModelsLayer.Users", "CreatedByUser")
                        .WithMany("Rout")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Cities", "FromCity")
                        .WithMany("RoutesFrom")
                        .HasForeignKey("FromCityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Countries", "FromCountry")
                        .WithMany("RoutesFrom")
                        .HasForeignKey("FromCountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Cities", "ToCity")
                        .WithMany("RoutesTo")
                        .HasForeignKey("ToCityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Countries", "ToCountry")
                        .WithMany("RoutesTo")
                        .HasForeignKey("ToCountryID");

                    b.Navigation("CreatedByUser");

                    b.Navigation("FromCity");

                    b.Navigation("FromCountry");

                    b.Navigation("ToCity");

                    b.Navigation("ToCountry");
                });

            modelBuilder.Entity("ModelsLayer.Tickets", b =>
                {
                    b.HasOne("ModelsLayer.Bookings", "Booking")
                        .WithMany("Ticket")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ModelsLayer.Trips", b =>
                {
                    b.HasOne("ModelsLayer.Buses", "Bus")
                        .WithMany("Trip")
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Users", "CreatedByUser")
                        .WithMany("Trip")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelsLayer.Routes", "Route")
                        .WithMany("Trip")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ModelsLayer.Bookings", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ModelsLayer.Buses", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("ModelsLayer.Cities", b =>
                {
                    b.Navigation("RoutesFrom");

                    b.Navigation("RoutesTo");
                });

            modelBuilder.Entity("ModelsLayer.Countries", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("RoutesFrom");

                    b.Navigation("RoutesTo");
                });

            modelBuilder.Entity("ModelsLayer.Customers", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ModelsLayer.CustomersCountries", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ModelsLayer.Drivers", b =>
                {
                    b.Navigation("Bus");
                });

            modelBuilder.Entity("ModelsLayer.Routes", b =>
                {
                    b.Navigation("RoutePrice");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("ModelsLayer.Trips", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ModelsLayer.Users", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Rout");

                    b.Navigation("RoutPrice");

                    b.Navigation("Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
